# action.yml
name: 'Authenticate to Huawei Cloud'
description: 'Authenticate to Huawei Cloud from GitHub Actions via AK/SK.'
inputs:
  access_key:
    description: "Access key id"
    required: true
  secret_key:
    description: "Secret access key"
    required: true
  project_id:
    description: "项目ID，可以在华为云我的凭证获取"
    required: false
  region:
    description: 'Region'
    required: false
    default: 'cn-north-4'
branding:
  icon: 'cloud'
  color: 'red'
runs:
  using: 'node16'
  main: 'dist/index.js'

